package g_code_generator_ui.model;

/**
 * AltiumSMTComponent Class provides functionality for storing and manipulating component attributes
 * that have been generated by an Altium PCB design
 * @author Justin Johnson
 *
 */
public class AltiumSMTComponent extends SMTComponent{

	/**
	 * Constructor creates instance of EagleSMTComponent
	 * Component attributes and attribute titles are assigned
	 * @param attributes String array containing EagleSMTComponent attributes
	 */
	public AltiumSMTComponent(String[] attributes) {
		super(attributes);
		super.attributeTitles = this.attributeTitles;
		//first check if attribute list is valid for Altium component
		if(attributes.length == ATTRIBUTE_COUNT){
			stripUnits();
			refDesignator = attributeList[0];
			footprint = attributeList[1];
			xCoordinate = attributeList[2];
			yCoordinate = attributeList[3];
			xReference = attributeList[4];
			yReference = attributeList[5];
			xPad = attributeList[6];
			yPad = attributeList[7];
			boardSide = attributeList[8];
			rotation = attributeList[9];
			comment = attributeList[10];
			isValidComponent = true;
		}
		else{
			isValidComponent = false;
		}
		
		
	}

	/**
	 * Returns true if total number of attributes matches the expected number of attributes
	 * If attribute list contains more/less than is expected, return false
	 * @return true if attributeList.length == this.ATTRIBUTE_COUNT
	 */
	public boolean isValidComponent(){
		return isValidComponent;
	}
	
	/**
	 * Removes units from end of dimesion/size values
	 */
	private void stripUnits(){
		for(int i = 2; i < attributeList.length; i++){
			attributeList[i].replace("mil", " ");
		}
	}

	/**
	 * Get component reference designator
	 * @return String refDesignator
	 */
	public String getRefDesignator() {
		return refDesignator;
	}
	/**
	 * Set component reference designator
	 * @param String refDesignator component reference designator
	 */
	public void setRefDesignator(String refDesignator) {
		this.refDesignator = attributeList[0] = refDesignator;
	}
	/**
	 * Get component footprint value
	 * @return String footprint
	 */
	public String getFootprint() {
		return footprint;
	}
	/**
	 * Set component footprint
	 * @param String footprint
	 */
	public void setFootprint(String footprint) {
		this.footprint = attributeList[1] = footprint;
	}
	/**
	 * Get component X Coordinate
	 * @return String xCoordinate
	 */
	public String getxCoordinate() {
		return xCoordinate;
	}
	/**
	 * Set component X Coordinate
	 * @param String xCoordinate
	 */
	public void setxCoordinate(String xCoordinate) {
		this.xCoordinate = attributeList[2] = xCoordinate;
	}
	/**
	 * Get component Y Coordinate
	 * @return String yCoordinate
	 */
	public String getyCoordinate() {
		return yCoordinate;
	}
	/**
	 * Set component Y Coordinate
	 * @param String yCoordinate
	 */
	public void setyCoordinate(String yCoordinate) {
		this.yCoordinate = attributeList[3] = yCoordinate;
	}
	/**
	 * Get component X Reference
	 * @return String xReference
	 */
	public String getxReference() {
		return xReference;
	}
	/**
	 * Set component X Reference
	 * @param String xReference
	 */
	public void setxReference(String xReference) {
		this.xReference = attributeList[4] = xReference;
	}
	/**
	 * Get component Y Reference
	 * @return String yReference
	 */
	public String getyReference() {
		return yReference;
	}
	/**
	 * Set component Y Reference
	 * @param String yReference
	 */
	public void setyReference(String yReference) {
		this.yReference = attributeList[5] = yReference;
	}
	/**
	 * Get component X Pad
	 * @return String xPad
	 */
	public String getxPad() {
		return xPad;
	}
	/**
	 * Set component X Pad
	 * @param String xPad
	 */
	public void setxPad(String xPad) {
		this.xPad = attributeList[6] = xPad;
	}
	/**
	 * Get component Y Pad
	 * @return String yPad
	 */
	public String getyPad() {
		return yPad;
	}
	/**
	 * Set component Y Pad
	 * @param String yPad
	 */
	public void setyPad(String yPad) {
		this.yPad = attributeList[7] = yPad;
	}
	/**
	 * Get component board side
	 * @return String boardSide
	 */
	public String getBoardSide() {
		return boardSide;
	}
	/**
	 * Set component board side
	 * @param String boardSide
	 */
	public void setBoardSide(String boardSide) {
		this.boardSide = attributeList[8] = boardSide;
	}
	/**
	 * Get component angle of rotation
	 * @return String rotation
	 */
	public String getRotation() {
		return rotation;
	}
	/**
	 * Set component angle of rotation
	 * @param String rotation
	 */
	public void setRotation(String rotation) {
		this.rotation = attributeList[9] = rotation;
	}
	/**
	 * Get component comments
	 * @return String comment
	 */
	public String getComment() {
		return comment;
	}
	/**
	 * Set component comments
	 * @param String comment
	 */
	public void setComment(String comment) {
		this.comment = attributeList[10] = comment;
	}



	private String[] attributeTitles = {"Ref Designator", "Footprint", "X Coordinate", "Y Coordinate", 
			"X Reference", "Y Reference", "X Pad", "Y Pad", "Board Side", "Rotation", "Comment"};
	public static final int ATTRIBUTE_COUNT = 11;
	private String refDesignator;
	private String footprint;
	private String xCoordinate;
	private String yCoordinate;
	private String xReference;
	private String yReference;
	private String xPad;
	private String yPad;
	private String boardSide;
	private String rotation;
	private String comment;
	private boolean isValidComponent;
	
}
